"""
BookShook Bot — Database Seeder
Parses the original hardcoded GENRE_BOOKS data and inserts it into SQLite.
Deduplicates entries and reports statistics.

Usage:
    python seed_data.py
"""

import os
import sys
import logging

# Ensure config doesn't fail if .env is missing during seeding
# We only need DATABASE_PATH, not the API keys
os.environ.setdefault("TELEGRAM_BOT_TOKEN", "dummy")
os.environ.setdefault("GOOGLE_API_KEY", "dummy")
os.environ.setdefault("GOOGLE_CSE_ID", "dummy")
os.environ.setdefault("ADMIN_USER_ID", "0")

from database import init_db, insert_genre, insert_book, link_book_genre, get_book_count, get_genres

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

# ── Original hardcoded data (extracted from BookShook.py) ─────────────────────
# This is the same GENRE_BOOKS dictionary, used only for seeding.

GENRE_BOOKS = {
    "Fantasy": [
        "The Lord of the Rings - J.R.R. Tolkien",
        "A Game of Thrones - George R.R. Martin",
        "Harry Potter and the Sorcerer's Stone - J.K. Rowling",
        "The Name of the Wind - Patrick Rothfuss",
        "Mistborn - Brandon Sanderson",
        "The Hobbit - J.R.R. Tolkien",
        "The Way of Kings - Brandon Sanderson",
        "The Wheel of Time - Robert Jordan",
        "The Lies of Locke Lamora - Scott Lynch",
        "The Priory of the Orange Tree - Samantha Shannon",
        "The Once and Future King - T.H. White",
        "The Chronicles of Narnia - C.S. Lewis",
        "The Magicians - Lev Grossman",
        "The Bone Season - Samantha Shannon",
        "The Black Prism - Brent Weeks",
        "Good Omens - Neil Gaiman & Terry Pratchett",
        "The Silmarillion - J.R.R. Tolkien",
        "The Poppy War - R.F. Kuang",
        "The Blade Itself - Joe Abercrombie",
        "The Fifth Season - N.K. Jemisin",
        "The Last Unicorn - Peter S. Beagle",
        "The Earthsea Cycle - Ursula K. Le Guin",
        "The Inheritance Trilogy - N.K. Jemisin",
        "The Broken Empire Trilogy - Mark Lawrence",
        "The Stormlight Archive - Brandon Sanderson",
        "The Red Queen's War - Mark Lawrence",
        "The Witcher Series - Andrzej Sapkowski",
        "The Lightbringer Series - Brent Weeks",
        "The Malazan Book of the Fallen - Steven Erikson",
        "The Dresden Files - Jim Butcher",
        "The Farseer Trilogy - Robin Hobb",
        "The Tawny Man Trilogy - Robin Hobb",
        "The Liveship Traders Trilogy - Robin Hobb",
        "The Riyria Revelations - Michael J. Sullivan",
        "The Faithful and the Fallen - John Gwynne",
        "The Powder Mage Trilogy - Brian McClellan",
        "The Gentleman Bastard Series - Scott Lynch",
        "The First Law Trilogy - Joe Abercrombie",
        "The Broken Earth Trilogy - N.K. Jemisin",
        "The Shadow of the Wind - Carlos Ruiz Zafón",
        "Jonathan Strange & Mr Norrell - Susanna Clarke",
        "The Girl Who Drank the Moon - Kelly Barnhill",
        "The Golden Compass - Philip Pullman",
        "The Subtle Knife - Philip Pullman",
        "The Amber Spyglass - Philip Pullman",
        "The Golem and the Jinni - Helene Wecker",
        "Uprooted - Naomi Novik",
        "Spinning Silver - Naomi Novik",
        "The Bear and the Nightingale - Katherine Arden",
        "The Night Circus - Erin Morgenstern",
        "The City of Brass - S.A. Chakraborty",
        "The Gilded Wolves - Roshani Chokshi",
        "Serpent & Dove - Shelby Mahurin",
        "An Ember in the Ashes - Sabaa Tahir",
        "Children of Blood and Bone - Tomi Adeyemi",
        "Shadow and Bone - Leigh Bardugo",
        "Six of Crows - Leigh Bardugo",
        "Crooked Kingdom - Leigh Bardugo",
        "The Cruel Prince - Holly Black",
        "The Queen of Nothing - Holly Black",
        "A Court of Thorns and Roses - Sarah J. Maas",
        "A Court of Mist and Fury - Sarah J. Maas",
        "A Court of Wings and Ruin - Sarah J. Maas",
        "Throne of Glass - Sarah J. Maas",
        "Crown of Midnight - Sarah J. Maas",
        "Heir of Fire - Sarah J. Maas",
        "Queen of Shadows - Sarah J. Maas",
        "Empire of Storms - Sarah J. Maas",
        "Tower of Dawn - Sarah J. Maas",
        "Kingdom of Ash - Sarah J. Maas",
        "The Iron King - Julie Kagawa",
        "The Iron Daughter - Julie Kagawa",
        "The Iron Queen - Julie Kagawa",
        "The Iron Knight - Julie Kagawa",
        "The Song of Achilles - Madeline Miller",
        "Circe - Madeline Miller",
        "The House in the Cerulean Sea - TJ Klune",
        "The Invisible Life of Addie LaRue - V.E. Schwab",
        "A Darker Shade of Magic - V.E. Schwab",
        "A Gathering of Shadows - V.E. Schwab",
        "A Conjuring of Light - V.E. Schwab",
        "The Ocean at the End of the Lane - Neil Gaiman",
        "Neverwhere - Neil Gaiman",
        "American Gods - Neil Gaiman",
        "Stardust - Neil Gaiman",
        "Coraline - Neil Gaiman",
        "The Graveyard Book - Neil Gaiman",
        "The Color of Magic - Terry Pratchett",
        "Guards! Guards! - Terry Pratchett",
        "Mort - Terry Pratchett",
        "Hogfather - Terry Pratchett",
        "Small Gods - Terry Pratchett",
        "The Sword of Shannara - Terry Brooks",
        "Elantris - Brandon Sanderson",
        "Warbreaker - Brandon Sanderson",
        "The Emperor's Soul - Brandon Sanderson",
        "The Rook - Daniel O'Malley",
        "The Library at Mount Char - Scott Hawkins",
        "The Rage of Dragons - Evan Winter",
        "The Bone Ships - RJ Barker",
        "The Ninth House - Leigh Bardugo",
        "The Atlas Six - Olivie Blake",
        "Fourth Wing - Rebecca Yarros",
        "Iron Flame - Rebecca Yarros",
    ],
    "Sci-Fi": [
        "Dune - Frank Herbert",
        "Ender's Game - Orson Scott Card",
        "Foundation - Isaac Asimov",
        "Neuromancer - William Gibson",
        "The Left Hand of Darkness - Ursula K. Le Guin",
        "Snow Crash - Neal Stephenson",
        "Hyperion - Dan Simmons",
        "The Martian - Andy Weir",
        "The Three-Body Problem - Liu Cixin",
        "The Hitchhiker's Guide to the Galaxy - Douglas Adams",
        "Brave New World - Aldous Huxley",
        "1984 - George Orwell",
        "Fahrenheit 451 - Ray Bradbury",
        "Do Androids Dream of Electric Sheep? - Philip K. Dick",
        "I, Robot - Isaac Asimov",
        "Kindred - Octavia E. Butler",
        "Red Mars - Kim Stanley Robinson",
        "Old Man's War - John Scalzi",
        "Altered Carbon - Richard K. Morgan",
        "The Dispossessed - Ursula K. Le Guin",
        "Contact - Carl Sagan",
        "Solaris - Stanislaw Lem",
        "Ringworld - Larry Niven",
        "The Forever War - Joe Haldeman",
        "The Time Machine - H.G. Wells",
        "Starship Troopers - Robert A. Heinlein",
        "The Windup Girl - Paolo Bacigalupi",
        "The Expanse Series - James S.A. Corey",
        "The Space Between Worlds - Micaiah Johnson",
        "A Canticle for Leibowitz - Walter M. Miller Jr.",
        "The Road - Cormac McCarthy",
        "Station Eleven - Emily St. John Mandel",
        "The Power - Naomi Alderman",
        "The Hunger Games - Suzanne Collins",
        "Parable of the Sower - Octavia E. Butler",
        "Never Let Me Go - Kazuo Ishiguro",
        "The Giver - Lois Lowry",
        "Ready Player One - Ernest Cline",
        "The Handmaid's Tale - Margaret Atwood",
        "The Girl With All the Gifts - M.R. Carey",
        "Children of Time - Adrian Tchaikovsky",
        "Blindsight - Peter Watts",
        "The Moon is a Harsh Mistress - Robert A. Heinlein",
        "The Stars My Destination - Alfred Bester",
        "The Long Way to a Small, Angry Planet - Becky Chambers",
        "Binti - Nnedi Okofor",
        "Ancillary Justice - Ann Leckie",
        "The Sparrow - Mary Doria Russell",
        "The Passage - Justin Cronin",
        "Dark Matter - Blake Crouch",
        "Recursion - Blake Crouch",
        "The Water Knife - Paolo Bacigalupi",
        "Wool - Hugh Howey",
        "The Maze Runner - James Dashner",
        "Oryx and Crake - Margaret Atwood",
        "The Stand - Stephen King",
        "The Man in the High Castle - Philip K. Dick",
        "The Andromeda Strain - Michael Crichton",
        "Jurassic Park - Michael Crichton",
        "Sphere - Michael Crichton",
        "Timeline - Michael Crichton",
        "The Children of Men - P.D. James",
        "Logan's Run - William F. Nolan",
        "Red Rising - Pierce Brown",
        "Golden Son - Pierce Brown",
        "Morning Star - Pierce Brown",
        "Cinder - Marissa Meyer",
        "Leviathan Wakes - James S.A. Corey",
        "Caliban's War - James S.A. Corey",
        "Abaddon's Gate - James S.A. Corey",
        "Persepolis Rising - James S.A. Corey",
        "Pandora's Star - Peter F. Hamilton",
        "The Reality Dysfunction - Peter F. Hamilton",
        "The First Fifteen Lives of Harry August - Claire North",
        "The Light of Other Days - Arthur C. Clarke & Stephen Baxter",
        "Childhood's End - Arthur C. Clarke",
        "Rendezvous with Rama - Arthur C. Clarke",
        "The City & The City - China Miéville",
        "The Book of the New Sun - Gene Wolfe",
        "The Demolished Man - Alfred Bester",
        "The Sirens of Titan - Kurt Vonnegut",
        "Slaughterhouse-Five - Kurt Vonnegut",
        "The Lathe of Heaven - Ursula K. Le Guin",
        "The Stars Are Legion - Kameron Hurley",
        "The Gone World - Tom Sweterlitsch",
        "The Quantum Thief - Hannu Rajaniemi",
        "Spin - Robert Charles Wilson",
        "The Player of Games - Iain M. Banks",
        "Consider Phlebas - Iain M. Banks",
        "Surface Detail - Iain M. Banks",
        "Diaspora - Greg Egan",
        "Permutation City - Greg Egan",
        "The Diamond Age - Neal Stephenson",
        "Cryptonomicon - Neal Stephenson",
        "The Peripheral - William Gibson",
        "Count Zero - William Gibson",
        "Pattern Recognition - William Gibson",
        "The Postmortal - Drew Magary",
        "The Silent Stars Go By - James S.A. Corey",
    ],
    "Romance": [
        "Pride and Prejudice - Jane Austen",
        "Jane Eyre - Charlotte Brontë",
        "Outlander - Diana Gabaldon",
        "The Fault in Our Stars - John Green",
        "Me Before You - Jojo Moyes",
        "The Notebook - Nicholas Sparks",
        "Twilight - Stephenie Meyer",
        "The Hating Game - Sally Thorne",
        "The Kiss Quotient - Helen Hoang",
        "Red, White & Royal Blue - Casey McQuiston",
        "The Rosie Project - Graeme Simsion",
        "The Wedding Date - Jasmine Guillory",
        "It Ends with Us - Colleen Hoover",
        "Ugly Love - Colleen Hoover",
        "November 9 - Colleen Hoover",
        "The Spanish Love Deception - Elena Armas",
        "Beach Read - Emily Henry",
        "People We Meet on Vacation - Emily Henry",
        "Book Lovers - Emily Henry",
        "The Love Hypothesis - Ali Hazelwood",
        "Beautiful Disaster - Jamie McGuire",
        "Fifty Shades of Grey - E.L. James",
        "To All the Boys I've Loved Before - Jenny Han",
        "Anna and the French Kiss - Stephanie Perkins",
        "The Selection - Kiera Cass",
        "The Duke and I - Julia Quinn",
        "The Viscount Who Loved Me - Julia Quinn",
        "The Wall of Winnipeg and Me - Mariana Zapata",
        "Wait for It - Mariana Zapata",
        "The Simple Wild - K.A. Tucker",
        "Archer's Voice - Mia Sheridan",
        "Reminders of Him - Colleen Hoover",
        "Confess - Colleen Hoover",
        "Slammed - Colleen Hoover",
        "Hopeless - Colleen Hoover",
        "The Deal - Elle Kennedy",
        "The Score - Elle Kennedy",
        "The Mistake - Elle Kennedy",
        "The Goal - Elle Kennedy",
        "The Bromance Book Club - Lyssa Kay Adams",
        "The Unhoneymooners - Christina Lauren",
        "Love and Other Words - Christina Lauren",
        "Josh and Hazel's Guide to Not Dating - Christina Lauren",
        "The Flatshare - Beth O'Leary",
        "The Switch - Beth O'Leary",
        "The Road Trip - Beth O'Leary",
        "The Soulmate Equation - Christina Lauren",
        "The Friend Zone - Abby Jimenez",
        "Life's Too Short - Abby Jimenez",
        "The Happy Ever After Playlist - Abby Jimenez",
        "The Wedding Party - Jasmine Guillory",
        "The Proposal - Jasmine Guillory",
        "The Bride Test - Helen Hoang",
        "The Heart Principle - Helen Hoang",
        "Fix Her Up - Tessa Bailey",
        "Love Her or Lose Her - Tessa Bailey",
        "It Happened One Summer - Tessa Bailey",
        "Hook, Line, and Sinker - Tessa Bailey",
        "The Perfect Hope - Nora Roberts",
        "Vision in White - Nora Roberts",
        "Bed of Roses - Nora Roberts",
        "Savor the Moment - Nora Roberts",
        "Happy Place - Emily Henry",
        "Things We Never Got Over - Lucy Score",
        "Things We Hide from the Light - Lucy Score",
        "The Cheat Sheet - Sarah Adams",
        "Twisted Love - Ana Huang",
        "Twisted Games - Ana Huang",
        "Twisted Lies - Ana Huang",
        "Twisted Hate - Ana Huang",
        "The Summer I Turned Pretty - Jenny Han",
        "It's Not Summer Without You - Jenny Han",
        "We'll Always Have Summer - Jenny Han",
        "Daisy Jones & The Six - Taylor Jenkins Reid",
        "The Seven Husbands of Evelyn Hugo - Taylor Jenkins Reid",
        "One True Loves - Taylor Jenkins Reid",
        "Maybe in Another Life - Taylor Jenkins Reid",
        "After - Anna Todd",
        "After We Collided - Anna Todd",
        "After We Fell - Anna Todd",
        "After Ever Happy - Anna Todd",
        "Beautiful Bastard - Christina Lauren",
        "Beautiful Stranger - Christina Lauren",
        "Beautiful Player - Christina Lauren",
        "Beautiful Secret - Christina Lauren",
        "The Duchess Deal - Tessa Dare",
        "The Wallflower Wager - Tessa Dare",
        "Romancing the Duke - Tessa Dare",
        "The Governess Game - Tessa Dare",
    ],
    "Mystery": [
        "Gone Girl - Gillian Flynn",
        "The Girl with the Dragon Tattoo - Stieg Larsson",
        "The Da Vinci Code - Dan Brown",
        "Big Little Lies - Liane Moriarty",
        "The Thursday Murder Club - Richard Osman",
        "The Woman in White - Wilkie Collins",
        "The Woman in Cabin 10 - Ruth Ware",
        "The Silent Patient - Alex Michaelides",
        "The Reversal - Michael Connelly",
        "The Cuckoo's Calling - Robert Galbraith",
        "The Hound of the Baskervilles - Arthur Conan Doyle",
        "The Murder of Roger Ackroyd - Agatha Christie",
        "The Secret History - Donna Tartt",
        "The No. 1 Ladies' Detective Agency - Alexander McCall Smith",
        "The Mysterious Affair at Styles - Agatha Christie",
        "The Moonstone - Wilkie Collins",
        "The Maltese Falcon - Dashiell Hammett",
        "The Big Sleep - Raymond Chandler",
        "The Postman Always Rings Twice - James M. Cain",
        "The Girl on the Train - Paula Hawkins",
        "The Woman in the Window - A.J. Finn",
        "Before I Go to Sleep - S.J. Watson",
        "The Wife Between Us - Greer Hendricks & Sarah Pekkanen",
        "The Couple Next Door - Shari Lapena",
        "The Dry - Jane Harper",
        "Still Life - Louise Penny",
        "In the Woods - Tana French",
        "The Secret Place - Tana French",
        "Sharp Objects - Gillian Flynn",
        "The Snowman - Jo Nesbø",
        "The Lincoln Rhyme Series - Jeffery Deaver",
        "The Inspector Gamache Series - Louise Penny",
        "The Millennium Trilogy - Stieg Larsson",
        "The Reacher Series - Lee Child",
        "The Poirot Series - Agatha Christie",
        "The Miss Marple Series - Agatha Christie",
        "The Sherlock Holmes Series - Arthur Conan Doyle",
        "The Alex Cross Series - James Patterson",
        "The Inspector Lynley Series - Elizabeth George",
        "The Inspector Banks Series - Peter Robinson",
        "The Inspector Wexford Series - Ruth Rendell",
        "The Inspector Morse Series - Colin Dexter",
        "The Inspector Rebus Series - Ian Rankin",
        "The Inspector Maigret Series - Georges Simenon",
        "The Inspector Alleyn Series - Ngaio Marsh",
        "The Inspector Dalgliesh Series - P.D. James",
        "The Inspector Jury Series - Martha Grimes",
        "The Inspector Pitt Series - Anne Perry",
        "The Inspector Rutledge Series - Charles Todd",
        "The Inspector West Series - John Creasey",
        "The Inspector Ghote Series - H.R.F. Keating",
        "The Inspector Chen Series - Qiu Xiaolong",
        "The Inspector Espinosa Series - Luiz Alfredo Garcia-Roza",
        "The Inspector Erlendur Series - Arnaldur Indriðason",
        "The Inspector Salvo Montalbano Series - Andrea Camilleri",
        "The Inspector Wallander Series - Henning Mankell",
    ],
    "Horror": [
        "It - Stephen King",
        "The Shining - Stephen King",
        "Dracula - Bram Stoker",
        "Frankenstein - Mary Shelley",
        "The Haunting of Hill House - Shirley Jackson",
        "Bird Box - Josh Malerman",
        "The Exorcist - William Peter Blatty",
        "The Silence of the Lambs - Thomas Harris",
        "The Amityville Horror - Jay Anson",
        "The Woman in Black - Susan Hill",
        "Mexican Gothic - Silvia Moreno-Garcia",
        "House of Leaves - Mark Z. Danielewski",
        "The Girl Next Door - Jack Ketchum",
        "The Stand - Stephen King",
        "Pet Sematary - Stephen King",
        "The Turn of the Screw - Henry James",
        "The Ruins - Scott Smith",
        "World War Z - Max Brooks",
        "Let the Right One In - John Ajvide Lindqvist",
        "The Passage - Justin Cronin",
        "The Troop - Nick Cutter",
        "The Fisherman - John Langan",
        "NOS4A2 - Joe Hill",
        "Something Wicked This Way Comes - Ray Bradbury",
        "The Hellbound Heart - Clive Barker",
        "Carrion Comfort - Dan Simmons",
        "Salem's Lot - Stephen King",
        "The Ritual - Adam Nevill",
        "The Only Good Indians - Stephen Graham Jones",
        "The Elementals - Michael McDowell",
        "The Ballad of Black Tom - Victor LaValle",
        "The Hunger - Alma Katsu",
        "The Devil in Silver - Victor LaValle",
        "The Red Tree - Caitlín R. Kiernan",
        "The Little Stranger - Sarah Waters",
        "The Terror - Dan Simmons",
        "Coraline - Neil Gaiman",
        "The Graveyard Book - Neil Gaiman",
        "The Girl With All the Gifts - M.R. Carey",
        "The Deep - Nick Cutter",
        "The Cabin at the End of the World - Paul Tremblay",
        "A Head Full of Ghosts - Paul Tremblay",
        "Revival - Stephen King",
        "The Outsider - Stephen King",
        "Heart-Shaped Box - Joe Hill",
        "The Winter People - Jennifer McMahon",
        "The Good House - Tananarive Due",
        "The House Next Door - Anne Rivers Siddons",
        "Hex - Thomas Olde Heuvelt",
        "The Changeling - Victor LaValle",
        "The Descent - Jeff Long",
        "The House on the Borderland - William Hope Hodgson",
        "The Doll-Master and Other Tales of Terror - Joyce Carol Oates",
        "The Keep - F. Paul Wilson",
        "The Silent Companions - Laura Purcell",
        "The Silent Corner - Dean Koontz",
        "The Girl in 6E - A.R. Torre",
        "The Hiding Place - C.J. Tudor",
        "The Whisper Man - Alex North",
        "The Chalk Man - C.J. Tudor",
        "The Family Plot - Cherie Priest",
        "The Southern Book Club's Guide to Slaying Vampires - Grady Hendrix",
        "My Best Friend's Exorcism - Grady Hendrix",
        "We Have Always Lived in the Castle - Shirley Jackson",
        "The Lottery and Other Stories - Shirley Jackson",
        "The Drowning Girl - Caitlín R. Kiernan",
        "Penpal - Dathan Auerbach",
        "Final Girls - Riley Sager",
        "The Girl from the Well - Rin Chupeco",
        "The Girl Who Loved Tom Gordon - Stephen King",
        "The Girl in the Mirror - Rose Carlyle",
        "The Girl in the Spider's Web - David Lagercrantz",
        "The Girl on the Train - Paula Hawkins",
        "The Girl Who Played with Fire - Stieg Larsson",
        "The Girl Who Kicked the Hornet's Nest - Stieg Larsson",
        "The Girl Who Chased the Moon - Sarah Addison Allen",
        "The Girl Who Circumnavigated Fairyland in a Ship of Her Own Making - Catherynne M. Valente",
        "The Girl with the Louding Voice - Abi Daré",
        "The Girl with the Red Balloon - Katherine Locke",
        "The Girl with Seven Names - Hyeonseo Lee",
        "The Girl Who Drank the Moon - Kelly Barnhill",
        "The Girl Who Could Move Sh*t with Her Mind - Jackson Ford",
        "The Girl Who Knew Too Much - Amanda Quick",
        "The Girl Who Played Go - Shan Sa",
        "The Girl Who Saved the King of Sweden - Jonas Jonasson",
        "The Girl Who Smiled Beads - Clemantine Wamariya",
        "The Girl Who Stopped Swimming - Joshilyn Jackson",
        "The Girl Who Takes an Eye for an Eye - David Lagercrantz",
        "The Girl Who Was Saturday Night - Heather O'Neill",
        "The Girl Who Wrote in Silk - Kelli Estes",
    ],
    "Philosophy": [
        "Meditations - Marcus Aurelius",
        "The Republic - Plato",
        "Beyond Good and Evil - Friedrich Nietzsche",
        "The Art of War - Sun Tzu",
        "The Stranger - Albert Camus",
        "Man's Search for Meaning - Viktor Frankl",
        "Sophie's World - Jostein Gaarder",
        "Nicomachean Ethics - Aristotle",
        "The Myth of Sisyphus - Albert Camus",
        "Thus Spoke Zarathustra - Friedrich Nietzsche",
        "Critique of Pure Reason - Immanuel Kant",
        "The Prince - Niccolò Machiavelli",
        "Being and Time - Martin Heidegger",
        "The Tao Te Ching - Laozi",
        "Walden - Henry David Thoreau",
        "The Analects - Confucius",
        "Letters from a Stoic - Seneca",
        "On the Shortness of Life - Seneca",
        "The Symposium - Plato",
        "The Ethics - Baruch Spinoza",
        "The Problems of Philosophy - Bertrand Russell",
        "The Consolation of Philosophy - Boethius",
        "The World as Will and Representation - Arthur Schopenhauer",
        "Tractatus Logico-Philosophicus - Ludwig Wittgenstein",
        "The Communist Manifesto - Karl Marx & Friedrich Engels",
        "Civilization and Its Discontents - Sigmund Freud",
        "The Social Contract - Jean-Jacques Rousseau",
        "The Order of Things - Michel Foucault",
        "The Structure of Scientific Revolutions - Thomas S. Kuhn",
        "The Phenomenology of Spirit - G.W.F. Hegel",
        "The Birth of Tragedy - Friedrich Nietzsche",
        "On Liberty - John Stuart Mill",
        "Utilitarianism - John Stuart Mill",
        "On the Genealogy of Morals - Friedrich Nietzsche",
        "The Will to Power - Friedrich Nietzsche",
        "The Critique of Practical Reason - Immanuel Kant",
        "The Critique of Judgment - Immanuel Kant",
        "The Gay Science - Friedrich Nietzsche",
        "The Antichrist - Friedrich Nietzsche",
        "The Confessions - St. Augustine",
        "The Enneads - Plotinus",
        "Fear and Trembling - Søren Kierkegaard",
        "Either/Or - Søren Kierkegaard",
        "The Sickness Unto Death - Søren Kierkegaard",
        "The Concept of Anxiety - Søren Kierkegaard",
        "Being and Nothingness - Jean-Paul Sartre",
        "Existentialism Is a Humanism - Jean-Paul Sartre",
        "No Exit - Jean-Paul Sartre",
        "The Second Sex - Simone de Beauvoir",
        "The Ethics of Ambiguity - Simone de Beauvoir",
        "Discipline and Punish - Michel Foucault",
        "The Archaeology of Knowledge - Michel Foucault",
        "The History of Sexuality - Michel Foucault",
        "The Open Society and Its Enemies - Karl Popper",
        "The Logic of Scientific Discovery - Karl Popper",
        "The Road to Serfdom - F.A. Hayek",
        "The Poverty of Historicism - Karl Popper",
        "The End of History and the Last Man - Francis Fukuyama",
        "The Clash of Civilizations - Samuel P. Huntington",
        "The Blank Slate - Steven Pinker",
        "The Selfish Gene - Richard Dawkins",
    ],
    "Self-help": [
        "Atomic Habits - James Clear",
        "The Power of Now - Eckhart Tolle",
        "The 7 Habits of Highly Effective People - Stephen Covey",
        "How to Win Friends and Influence People - Dale Carnegie",
        "Think and Grow Rich - Napoleon Hill",
        "The Subtle Art of Not Giving a F*ck - Mark Manson",
        "Man's Search for Meaning - Viktor Frankl",
        "Deep Work - Cal Newport",
        "Can't Hurt Me - David Goggins",
        "Mindset - Carol S. Dweck",
        "Start With Why - Simon Sinek",
        "Make Your Bed - William H. McRaven",
        "The Four Agreements - Don Miguel Ruiz",
        "Who Moved My Cheese? - Spencer Johnson",
        "The Miracle Morning - Hal Elrod",
        "The Alchemist - Paulo Coelho",
        "The Magic of Thinking Big - David J. Schwartz",
        "Awaken the Giant Within - Tony Robbins",
        "Unlimited Power - Tony Robbins",
        "The Power of Habit - Charles Duhigg",
        "Grit - Angela Duckworth",
        "Drive - Daniel H. Pink",
        "Quiet - Susan Cain",
        "The Gifts of Imperfection - Brené Brown",
        "Daring Greatly - Brené Brown",
        "You Are a Badass - Jen Sincero",
        "The Life-Changing Magic of Tidying Up - Marie Kondo",
        "The Happiness Project - Gretchen Rubin",
        "The Confidence Code - Katty Kay & Claire Shipman",
        "The One Thing - Gary Keller",
        "Essentialism - Greg McKeown",
        "The Lean Startup - Eric Ries",
        "The 5 Second Rule - Mel Robbins",
        "Tools of Titans - Tim Ferriss",
        "The 4-Hour Workweek - Tim Ferriss",
        "The 4-Hour Body - Tim Ferriss",
        "The 4-Hour Chef - Tim Ferriss",
        "The Art of Happiness - Dalai Lama",
        "The Road Less Traveled - M. Scott Peck",
        "The Untethered Soul - Michael A. Singer",
        "The War of Art - Steven Pressfield",
        "Ego Is the Enemy - Ryan Holiday",
        "The Obstacle Is the Way - Ryan Holiday",
        "Stillness Is the Key - Ryan Holiday",
        "Mastery - Robert Greene",
        "The Laws of Human Nature - Robert Greene",
        "The 48 Laws of Power - Robert Greene",
        "The Art of Seduction - Robert Greene",
        "The 33 Strategies of War - Robert Greene",
        "The Daily Stoic - Ryan Holiday",
        "The Slight Edge - Jeff Olson",
        "The Compound Effect - Darren Hardy",
        "Eat That Frog! - Brian Tracy",
        "Getting Things Done - David Allen",
        "The Now Habit - Neil Fiore",
        "Flow - Mihaly Csikszentmihalyi",
        "The Willpower Instinct - Kelly McGonigal",
        "The Happiness Advantage - Shawn Achor",
        "The Success Principles - Jack Canfield",
        "The Miracle Equation - Hal Elrod",
        "The 10X Rule - Grant Cardone",
        "The Motivation Myth - Jeff Haden",
    ],
    "Classic": [
        "Pride and Prejudice - Jane Austen",
        "To Kill a Mockingbird - Harper Lee",
        "1984 - George Orwell",
        "Jane Eyre - Charlotte Brontë",
        "The Great Gatsby - F. Scott Fitzgerald",
        "Wuthering Heights - Emily Brontë",
        "Moby-Dick - Herman Melville",
        "War and Peace - Leo Tolstoy",
        "Anna Karenina - Leo Tolstoy",
        "Crime and Punishment - Fyodor Dostoevsky",
        "The Catcher in the Rye - J.D. Salinger",
        "Great Expectations - Charles Dickens",
        "Little Women - Louisa May Alcott",
        "The Odyssey - Homer",
        "The Iliad - Homer",
        "Les Misérables - Victor Hugo",
        "The Brothers Karamazov - Fyodor Dostoevsky",
        "Dracula - Bram Stoker",
        "Frankenstein - Mary Shelley",
        "Emma - Jane Austen",
        "Sense and Sensibility - Jane Austen",
        "Northanger Abbey - Jane Austen",
        "Persuasion - Jane Austen",
        "Oliver Twist - Charles Dickens",
        "David Copperfield - Charles Dickens",
        "Bleak House - Charles Dickens",
        "A Tale of Two Cities - Charles Dickens",
        "Vanity Fair - William Makepeace Thackeray",
        "The Picture of Dorian Gray - Oscar Wilde",
        "The Scarlet Letter - Nathaniel Hawthorne",
        "The Grapes of Wrath - John Steinbeck",
        "Of Mice and Men - John Steinbeck",
        "East of Eden - John Steinbeck",
        "The Old Man and the Sea - Ernest Hemingway",
        "A Farewell to Arms - Ernest Hemingway",
        "For Whom the Bell Tolls - Ernest Hemingway",
        "The Sun Also Rises - Ernest Hemingway",
        "Brave New World - Aldous Huxley",
        "Animal Farm - George Orwell",
        "Lord of the Flies - William Golding",
        "The Count of Monte Cristo - Alexandre Dumas",
        "The Three Musketeers - Alexandre Dumas",
        "Don Quixote - Miguel de Cervantes",
        "Madame Bovary - Gustave Flaubert",
        "The Hunchback of Notre-Dame - Victor Hugo",
        "Tess of the d'Urbervilles - Thomas Hardy",
        "Far from the Madding Crowd - Thomas Hardy",
        "The Mayor of Casterbridge - Thomas Hardy",
        "The Metamorphosis - Franz Kafka",
        "The Trial - Franz Kafka",
        "The Stranger - Albert Camus",
        "The Plague - Albert Camus",
        "The Bell Jar - Sylvia Plath",
        "Rebecca - Daphne du Maurier",
        "Gone with the Wind - Margaret Mitchell",
        "A Room with a View - E.M. Forster",
        "Howards End - E.M. Forster",
        "The Secret Garden - Frances Hodgson Burnett",
        "A Little Princess - Frances Hodgson Burnett",
        "The Wind in the Willows - Kenneth Grahame",
        "Black Beauty - Anna Sewell",
        "The Adventures of Huckleberry Finn - Mark Twain",
        "The Adventures of Tom Sawyer - Mark Twain",
        "The Call of the Wild - Jack London",
        "White Fang - Jack London",
        "The Jungle Book - Rudyard Kipling",
        "Kim - Rudyard Kipling",
        "The Wonderful Wizard of Oz - L. Frank Baum",
        "Alice's Adventures in Wonderland - Lewis Carroll",
        "Through the Looking-Glass - Lewis Carroll",
        "Treasure Island - Robert Louis Stevenson",
        "Kidnapped - Robert Louis Stevenson",
        "Dr. Jekyll and Mr. Hyde - Robert Louis Stevenson",
        "The Secret Agent - Joseph Conrad",
        "Heart of Darkness - Joseph Conrad",
        "Lord Jim - Joseph Conrad",
        "The Scarlet Pimpernel - Baroness Orczy",
        "The Phantom of the Opera - Gaston Leroux",
        "Journey to the Center of the Earth - Jules Verne",
        "Twenty Thousand Leagues Under the Sea - Jules Verne",
        "Around the World in Eighty Days - Jules Verne",
        "The Time Machine - H.G. Wells",
        "The War of the Worlds - H.G. Wells",
        "The Invisible Man - H.G. Wells",
        "The Island of Doctor Moreau - H.G. Wells",
        "The House of Mirth - Edith Wharton",
        "Ethan Frome - Edith Wharton",
        "The Age of Innocence - Edith Wharton",
        "The Awakening - Kate Chopin",
        "The House of the Seven Gables - Nathaniel Hawthorne",
        "The Turn of the Screw - Henry James",
        "Washington Square - Henry James",
        "The Wings of the Dove - Henry James",
        "The Portrait of a Lady - Henry James",
    ],
    "Adventure": [
        "Treasure Island - Robert Louis Stevenson",
        "The Three Musketeers - Alexandre Dumas",
        "The Count of Monte Cristo - Alexandre Dumas",
        "The Hobbit - J.R.R. Tolkien",
        "Life of Pi - Yann Martel",
        "Into the Wild - Jon Krakauer",
        "The Odyssey - Homer",
        "Moby-Dick - Herman Melville",
        "The Call of the Wild - Jack London",
        "White Fang - Jack London",
        "Journey to the Center of the Earth - Jules Verne",
        "Twenty Thousand Leagues Under the Sea - Jules Verne",
        "Around the World in Eighty Days - Jules Verne",
        "The Lost World - Arthur Conan Doyle",
        "King Solomon's Mines - H. Rider Haggard",
        "The Jungle Book - Rudyard Kipling",
        "Kim - Rudyard Kipling",
        "The Swiss Family Robinson - Johann David Wyss",
        "Robinson Crusoe - Daniel Defoe",
        "The Adventures of Huckleberry Finn - Mark Twain",
        "The Adventures of Tom Sawyer - Mark Twain",
        "The Secret Garden - Frances Hodgson Burnett",
        "The Wind in the Willows - Kenneth Grahame",
        "The Black Stallion - Walter Farley",
        "The Prisoner of Zenda - Anthony Hope",
        "She - H. Rider Haggard",
        "The Man Who Would Be King - Rudyard Kipling",
        "The Thirty-Nine Steps - John Buchan",
        "The Scarlet Pimpernel - Baroness Orczy",
        "Beau Geste - P.C. Wren",
        "The Phantom of the Opera - Gaston Leroux",
        "The Island of Doctor Moreau - H.G. Wells",
        "The Time Machine - H.G. Wells",
        "The War of the Worlds - H.G. Wells",
        "The Invisible Man - H.G. Wells",
        "The House of the Seven Gables - Nathaniel Hawthorne",
        "The Coral Island - R.M. Ballantyne",
        "The Deerslayer - James Fenimore Cooper",
        "The Last of the Mohicans - James Fenimore Cooper",
        "The Pathfinder - James Fenimore Cooper",
        "The Pioneers - James Fenimore Cooper",
        "The Prairie - James Fenimore Cooper",
        "The Sea-Wolf - Jack London",
        "The Iron Heel - Jack London",
        "Tarzan of the Apes - Edgar Rice Burroughs",
        "The Gods of Mars - Edgar Rice Burroughs",
        "The Mysterious Island - Jules Verne",
        "The Black Arrow - Robert Louis Stevenson",
        "The Master of Ballantrae - Robert Louis Stevenson",
        "The Cossacks - Leo Tolstoy",
        "The White Company - Arthur Conan Doyle",
        "The Hound of the Baskervilles - Arthur Conan Doyle",
        "The Valley of Fear - Arthur Conan Doyle",
        "The Sign of Four - Arthur Conan Doyle",
        "The Memoirs of Sherlock Holmes - Arthur Conan Doyle",
        "The Return of Sherlock Holmes - Arthur Conan Doyle",
    ],
    "Friendship": [
        "Charlotte's Web - E.B. White",
        "The Kite Runner - Khaled Hosseini",
        "Bridge to Terabithia - Katherine Paterson",
        "Wonder - R.J. Palacio",
        "Anne of Green Gables - L.M. Montgomery",
        "Harry Potter Series - J.K. Rowling",
        "The Perks of Being a Wallflower - Stephen Chbosky",
        "A Man Called Ove - Fredrik Backman",
        "The Book Thief - Markus Zusak",
        "The Sisterhood of the Traveling Pants - Ann Brashares",
        "Because of Winn-Dixie - Kate DiCamillo",
        "The Outsiders - S.E. Hinton",
        "My Brilliant Friend - Elena Ferrante",
        "The Help - Kathryn Stockett",
        "Little Women - Louisa May Alcott",
        "Fried Green Tomatoes at the Whistle Stop Cafe - Fannie Flagg",
        "The Secret Garden - Frances Hodgson Burnett",
        "Matilda - Roald Dahl",
        "The Wind in the Willows - Kenneth Grahame",
        "To Kill a Mockingbird - Harper Lee",
        "The Fault in Our Stars - John Green",
        "Looking for Alaska - John Green",
        "Paper Towns - John Green",
        "The Giver - Lois Lowry",
        "The Hunger Games - Suzanne Collins",
        "The Golden Compass - Philip Pullman",
        "Anne Frank: The Diary of a Young Girl - Anne Frank",
        "The House on Mango Street - Sandra Cisneros",
        "The Little Prince - Antoine de Saint-Exupéry",
        "A Wrinkle in Time - Madeleine L'Engle",
        "The Chronicles of Narnia - C.S. Lewis",
        "The Lion, the Witch and the Wardrobe - C.S. Lewis",
        "The Secret Life of Bees - Sue Monk Kidd",
        "Holes - Louis Sachar",
        "The Watsons Go to Birmingham - Christopher Paul Curtis",
        "The Absolutely True Diary of a Part-Time Indian - Sherman Alexie",
        "The Curious Incident of the Dog in the Night-Time - Mark Haddon",
        "The Boy in the Striped Pajamas - John Boyne",
        "The Lightning Thief - Rick Riordan",
        "Percy Jackson Series - Rick Riordan",
        "The Maze Runner - James Dashner",
        "The Outsiders - S.E. Hinton",
        "The Catcher in the Rye - J.D. Salinger",
        "The Lord of the Rings - J.R.R. Tolkien",
        "The Hobbit - J.R.R. Tolkien",
        "The Fellowship of the Ring - J.R.R. Tolkien",
        "The Two Towers - J.R.R. Tolkien",
        "The Return of the King - J.R.R. Tolkien",
        "The Great Gatsby - F. Scott Fitzgerald",
        "Of Mice and Men - John Steinbeck",
    ],
    "Coming-of-age": [
        "The Catcher in the Rye - J.D. Salinger",
        "To Kill a Mockingbird - Harper Lee",
        "The Perks of Being a Wallflower - Stephen Chbosky",
        "A Separate Peace - John Knowles",
        "Norwegian Wood - Haruki Murakami",
        "The Fault in Our Stars - John Green",
        "Looking for Alaska - John Green",
        "Paper Towns - John Green",
        "Eleanor & Park - Rainbow Rowell",
        "Speak - Laurie Halse Anderson",
        "The Outsiders - S.E. Hinton",
        "Anne of Green Gables - L.M. Montgomery",
        "Little Women - Louisa May Alcott",
        "Jane Eyre - Charlotte Brontë",
        "Great Expectations - Charles Dickens",
        "David Copperfield - Charles Dickens",
        "Oliver Twist - Charles Dickens",
        "Lord of the Flies - William Golding",
        "A Tree Grows in Brooklyn - Betty Smith",
        "Black Boy - Richard Wright",
        "The House on Mango Street - Sandra Cisneros",
        "Go Ask Alice - Anonymous",
        "The Absolutely True Diary of a Part-Time Indian - Sherman Alexie",
        "The Bell Jar - Sylvia Plath",
        "The Member of the Wedding - Carson McCullers",
        "I Know Why the Caged Bird Sings - Maya Angelou",
        "The Book Thief - Markus Zusak",
        "The Kite Runner - Khaled Hosseini",
        "A Portrait of the Artist as a Young Man - James Joyce",
        "The Adventures of Huckleberry Finn - Mark Twain",
        "The Adventures of Tom Sawyer - Mark Twain",
        "The Giver - Lois Lowry",
        "The Chocolate War - Robert Cormier",
        "Bridge to Terabithia - Katherine Paterson",
        "My Name Is Asher Lev - Chaim Potok",
        "The Secret Life of Bees - Sue Monk Kidd",
        "A Wrinkle in Time - Madeleine L'Engle",
        "The Diary of a Young Girl - Anne Frank",
        "The Bluest Eye - Toni Morrison",
        "The Color Purple - Alice Walker",
        "The Curious Incident of the Dog in the Night-Time - Mark Haddon",
        "Wonder - R.J. Palacio",
        "The Goldfinch - Donna Tartt",
        "The Glass Castle - Jeannette Walls",
    ],
    "Dystopia": [
        "1984 - George Orwell",
        "Brave New World - Aldous Huxley",
        "Fahrenheit 451 - Ray Bradbury",
        "The Handmaid's Tale - Margaret Atwood",
        "The Hunger Games - Suzanne Collins",
        "Divergent - Veronica Roth",
        "The Giver - Lois Lowry",
        "Never Let Me Go - Kazuo Ishiguro",
        "Station Eleven - Emily St. John Mandel",
        "The Maze Runner - James Dashner",
        "The Road - Cormac McCarthy",
        "Wool - Hugh Howey",
        "Oryx and Crake - Margaret Atwood",
        "Parable of the Sower - Octavia E. Butler",
        "The Children of Men - P.D. James",
        "The Power - Naomi Alderman",
        "Red Rising - Pierce Brown",
        "Golden Son - Pierce Brown",
        "Morning Star - Pierce Brown",
        "The Stand - Stephen King",
        "The Passage - Justin Cronin",
        "The City of Ember - Jeanne DuPrau",
        "The Long Walk - Stephen King",
        "The Running Man - Stephen King",
        "The Chrysalids - John Wyndham",
        "The Day of the Triffids - John Wyndham",
        "The Iron Heel - Jack London",
        "Do Androids Dream of Electric Sheep? - Philip K. Dick",
        "We - Yevgeny Zamyatin",
        "The Dispossessed - Ursula K. Le Guin",
        "Cloud Atlas - David Mitchell",
        "The Windup Girl - Paolo Bacigalupi",
        "The Water Knife - Paolo Bacigalupi",
        "The Man in the High Castle - Philip K. Dick",
        "The Book of M - Peng Shepherd",
        "The Bone Clocks - David Mitchell",
        "The Postmortal - Drew Magary",
        "The Unit - Ninni Holmqvist",
        "Blindness - José Saramago",
        "Gather the Daughters - Jennie Melamed",
        "The Girl With All the Gifts - M.R. Carey",
        "The Ballad of Songbirds and Snakes - Suzanne Collins",
        "Catching Fire - Suzanne Collins",
        "Mockingjay - Suzanne Collins",
        "Legend - Marie Lu",
        "Prodigy - Marie Lu",
        "Champion - Marie Lu",
        "The Selection - Kiera Cass",
        "The Elite - Kiera Cass",
        "The One - Kiera Cass",
        "Matched - Ally Condie",
        "Crossed - Ally Condie",
        "Reached - Ally Condie",
        "Delirium - Lauren Oliver",
        "Pandemonium - Lauren Oliver",
        "Requiem - Lauren Oliver",
        "Uglies - Scott Westerfeld",
        "Pretties - Scott Westerfeld",
        "Specials - Scott Westerfeld",
        "Extras - Scott Westerfeld",
        "Feed - M.T. Anderson",
        "The Knife of Never Letting Go - Patrick Ness",
        "The Ask and the Answer - Patrick Ness",
        "Monsters of Men - Patrick Ness",
    ],
}


def parse_book_entry(entry: str) -> tuple[str, str]:
    """
    Parse a 'Title - Author' string into (title, author).
    Handles edge cases like titles containing ' - '.
    """
    # Split on the LAST occurrence of ' - ' to handle titles with dashes
    parts = entry.rsplit(" - ", 1)
    if len(parts) == 2:
        return parts[0].strip(), parts[1].strip()
    # Fallback: treat entire string as title with unknown author
    return entry.strip(), "Unknown"


def seed_database():
    """Seed the database from the hardcoded GENRE_BOOKS data."""
    logger.info("=" * 60)
    logger.info("BookShook Database Seeder")
    logger.info("=" * 60)

    # Initialize tables
    init_db()

    total_entries = 0
    total_unique_books = 0
    total_links = 0
    duplicates_skipped = 0
    seen_books = set()  # Track (title, author) tuples for stats

    for genre_name, book_list in GENRE_BOOKS.items():
        genre_id = insert_genre(genre_name)
        genre_unique = 0
        genre_dupes = 0

        # Deduplicate within the genre list itself
        seen_in_genre = set()
        for entry in book_list:
            total_entries += 1
            title, author = parse_book_entry(entry)
            key = (title.lower(), author.lower())

            if key in seen_in_genre:
                genre_dupes += 1
                duplicates_skipped += 1
                continue
            seen_in_genre.add(key)

            book_id = insert_book(title, author)
            link_book_genre(book_id, genre_id)
            total_links += 1

            if key not in seen_books:
                seen_books.add(key)
                total_unique_books += 1
                genre_unique += 1

        logger.info(
            "  %-15s → %3d entries, %3d unique new books, %2d intra-genre duplicates removed",
            genre_name, len(book_list), genre_unique, genre_dupes
        )

    logger.info("-" * 60)
    logger.info("Total raw entries processed:    %d", total_entries)
    logger.info("Total unique books in database: %d", total_unique_books)
    logger.info("Total genre-book links:         %d", total_links)
    logger.info("Duplicates skipped:             %d", duplicates_skipped)
    logger.info("Genres created:                 %d", len(GENRE_BOOKS))
    logger.info("=" * 60)
    logger.info("✅ Database seeded successfully at: %s",
                os.path.join(os.path.dirname(os.path.abspath(__file__)), "books.db"))


if __name__ == "__main__":
    seed_database()
